spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hufsting
    username: huigwan
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 386676289031-rh4v08860ffopeip90l4ss5en08ot4d6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: info
    org.zercok: debug
    org.springframework.security: debug

org:
  zerock:
    jwt:
      secret: hi123456789

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**