spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hufsting
    username: huigwan
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 753499212823-ftql7ed4h06gcbm8rrtrbmgg0h5odttl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/auth/google/callback
            scope:
              - profile
              - email

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: info
    org.zercok: debug
    org.springframework.security: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**