INSERT INTO member (MEMBER_NAME, MEMBER_MAJOR, MEMBER_EMAIL, MEMBER_PWD, MEMBER_ROLE, PROFILE_SET_UP_STATUS) VALUES ('홍길동', '컴전', 'dksk12@hufs.ac.kr', 'password123', 'ROLE_USER', FALSE);
INSERT INTO member (MEMBER_NAME, MEMBER_MAJOR, MEMBER_EMAIL, MEMBER_PWD, MEMBER_ROLE, PROFILE_SET_UP_STATUS) VALUES ('이순신', '컴전', 'dksk123@hufs.ac.kr', 'password123', 'ROLE_USER', FALSE);
INSERT INTO member (MEMBER_NAME, MEMBER_MAJOR, MEMBER_EMAIL, MEMBER_PWD, MEMBER_ROLE, PROFILE_SET_UP_STATUS) VALUES ('세종대왕', '컴전', 'dksk1234@hufs.ac.kr', 'password123', 'ROLE_USER', FALSE);
INSERT INTO PROFILE (PROFILE_GENDER, PROFILE_STUDENTNUMBER, PROFILE_MBTI, PROFILE_BIRTHDAY, PROFILE_CONTENT, MEMBER_ID)
VALUES ('MALE', '20210001', 'INTJ', '2000-01-01', '저는 홍길동입니다.', 1);
INSERT INTO PROFILE (PROFILE_GENDER, PROFILE_STUDENTNUMBER, PROFILE_MBTI, PROFILE_BIRTHDAY, PROFILE_CONTENT, MEMBER_ID)
VALUES ('MALE', '20210002', 'INTJ', '2000-01-02', '저는 이순신입니다.', 2);
INSERT INTO PROFILE (PROFILE_GENDER, PROFILE_STUDENTNUMBER, PROFILE_MBTI, PROFILE_BIRTHDAY, PROFILE_CONTENT, MEMBER_ID)
VALUES ('MALE', '20210003', 'INTJ', '2000-01-03', '저는 세종대왕입니다.', 3);